package handler

import (
	"context"

	"github.com/Nha1410/go-zero-template/service/user/internal/logic"
	"github.com/Nha1410/go-zero-template/service/user/internal/svc"
	"github.com/Nha1410/go-zero-template/service/user/userclient"
)

type UserHandler struct {
	svcCtx *svc.ServiceContext
}

func NewUserHandler(svcCtx *svc.ServiceContext) *UserHandler {
	return &UserHandler{
		svcCtx: svcCtx,
	}
}

// RegisterHandlers will be auto-generated by goctl after running:
// ./scripts/generate-service.sh user
// The generated code will register the gRPC service handlers

// CreateUser handles CreateUser gRPC request
func (h *UserHandler) CreateUser(ctx context.Context, req *userclient.CreateUserReq) (*userclient.CreateUserResp, error) {
	l := logic.NewCreateUserLogic(ctx, h.svcCtx)
	return l.CreateUser(req)
}

// GetUser handles GetUser gRPC request
func (h *UserHandler) GetUser(ctx context.Context, req *userclient.GetUserReq) (*userclient.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, h.svcCtx)
	return l.GetUser(req)
}

// GetUsers handles GetUsers gRPC request
func (h *UserHandler) GetUsers(ctx context.Context, req *userclient.GetUsersReq) (*userclient.GetUsersResp, error) {
	l := logic.NewGetUsersLogic(ctx, h.svcCtx)
	return l.GetUsers(req)
}

// UpdateUser handles UpdateUser gRPC request
func (h *UserHandler) UpdateUser(ctx context.Context, req *userclient.UpdateUserReq) (*userclient.UpdateUserResp, error) {
	l := logic.NewUpdateUserLogic(ctx, h.svcCtx)
	return l.UpdateUser(req)
}

// DeleteUser handles DeleteUser gRPC request
func (h *UserHandler) DeleteUser(ctx context.Context, req *userclient.DeleteUserReq) (*userclient.DeleteUserResp, error) {
	l := logic.NewDeleteUserLogic(ctx, h.svcCtx)
	return l.DeleteUser(req)
}
