package types

// This file will be auto-generated by goctl from api.api file
// Keeping this as placeholder for now

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    any    `json:"data,omitempty"`
}

type User struct {
	Id        int64  `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type CreateUserRequest struct {
	Email string `json:"email" validate:"required,email"`
	Name  string `json:"name" validate:"required"`
}

type UpdateUserRequest struct {
	Id    int64  `json:"id" validate:"required"`
	Email string `json:"email,omitempty" validate:"omitempty,email"`
	Name  string `json:"name,omitempty"`
}

type GetUserRequest struct {
	Id    string `path:"id"`
	IdInt int64  // Parsed ID
}

type GetUsersRequest struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=10"`
}

type DeleteUserRequest struct {
	Id int64 `path:"id"`
}

