// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. It will be replaced when you run:
// ./scripts/generate-service.sh user
//
// To generate the actual code, run:
// goctl rpc protoc service/user/user.proto --go_out=service/user --go-grpc_out=service/user --zrpc_out=service/user --style gozero

package userclient

import "context"

// Request/Response messages - these will be generated from proto
type CreateUserReq struct {
	Email string
	Name  string
}

type CreateUserResp struct {
	Id        int64
	Email     string
	Name      string
	CreatedAt string
}

type GetUserReq struct {
	Id int64
}

type GetUserResp struct {
	Id        int64
	Email     string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type GetUsersReq struct {
	Page     int64
	PageSize int64
}

type GetUsersResp struct {
	Users    []*GetUserResp
	Total    int64
	Page     int64
	PageSize int64
}

type UpdateUserReq struct {
	Id    int64
	Email string
	Name  string
}

type UpdateUserResp struct {
	Id        int64
	Email     string
	Name      string
	UpdatedAt string
}

type DeleteUserReq struct {
	Id int64
}

type DeleteUserResp struct {
	Success bool
}

// User service client interface - will be generated from proto
type User interface {
	CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserResp, error)
	GetUser(ctx context.Context, req *GetUserReq) (*GetUserResp, error)
	GetUsers(ctx context.Context, req *GetUsersReq) (*GetUsersResp, error)
	UpdateUser(ctx context.Context, req *UpdateUserReq) (*UpdateUserResp, error)
	DeleteUser(ctx context.Context, req *DeleteUserReq) (*DeleteUserResp, error)
}

// NewUser creates a new user client - will be generated from proto
func NewUser(conn interface{}) User {
	// Placeholder implementation - will be replaced by generated code
	return &userClient{}
}

// Placeholder implementation
type userClient struct{}

func (c *userClient) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserResp, error) {
	return nil, nil
}

func (c *userClient) GetUser(ctx context.Context, req *GetUserReq) (*GetUserResp, error) {
	return nil, nil
}

func (c *userClient) GetUsers(ctx context.Context, req *GetUsersReq) (*GetUsersResp, error) {
	return nil, nil
}

func (c *userClient) UpdateUser(ctx context.Context, req *UpdateUserReq) (*UpdateUserResp, error) {
	return nil, nil
}

func (c *userClient) DeleteUser(ctx context.Context, req *DeleteUserReq) (*DeleteUserResp, error) {
	return nil, nil
}
